#!/bin/bash
set -e
set -o pipefail

# Host bootstrap. $HOST_TYPE/cloud-init.yaml runs this from runcmd at bootstrap,
# where stdin is not a tty, so nothing here may ask a question: this script does
# only what a fresh droplet needs, and does it unattended.
#
# Everything that belongs to the NFS share rather than to this droplet -- the
# data directories, the TLS material, the certificate -- lives in ~/init-data.sh
# instead. The share outlives any one box, so that is run by hand once per share
# and not at bootstrap. Re-running this script is harmless.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/common.sh"

echo "=== Checking $DATA_DIR ==="
require_data_mount

echo "=== Cloning thevenin-nginx into $REPO_DIR ==="
mkdir -p "$HOME/git"
if [ -d "$REPO_DIR/.git" ]; then
  git -C "$REPO_DIR" pull --ff-only
else
  git clone https://github.com/xinxinw1/thevenin-nginx.git "$REPO_DIR"
fi

cd "$REPO_DIR"

# The stack's two inputs. thevenin-nginx deliberately ships no values for them,
# so this is where they are decided. Rewritten on every run, so changing one
# above and re-running is enough. It goes after the pull, not before: the file
# is gitignored over there, and that is the order that keeps it so.
echo "=== Writing .env ==="
cat > .env <<EOF
# Generated by ~/setup.sh for host type $HOST_TYPE. Edit setup.sh, not this file.
DATA_DIR=$DATA_DIR
SITE_DOMAIN=$DOMAIN
EOF

# Kept here rather than in init-data.sh even though it is the mysql password:
# docker compose reads it as an env_file and will not start the stack without
# it, and it lives on the droplet's own disk, not on the share. Only a fresh
# mysql data directory honors it, so on a rebuild against an existing share the
# newly generated one is written but never takes effect -- the share's own
# password stays in force, and is the one to keep.
if [ ! -f .env.secrets ]; then
  echo "=== Generating .env.secrets ==="
  MYSQL_ROOT_PASSWORD="$(openssl rand -base64 24)"
  printf 'MYSQL_ROOT_PASSWORD=%s\n' "$MYSQL_ROOT_PASSWORD" > .env.secrets
  chmod 600 .env.secrets
  echo "Generated a mysql root password. Save it somewhere safe:"
  echo "  $MYSQL_ROOT_PASSWORD"
  echo "(It only takes effect on a fresh mysql data directory. An existing"
  echo "share keeps whatever password it already has.) It stays readable in"
  echo "  $REPO_DIR/.env.secrets"
fi

# Starting the stack against an uninitialized share would have docker create the
# bind-mount sources itself, root-owned and mode 0755 -- which text-edit, running
# as an unknown uid, cannot write uploads into. Better to stop and say so: the
# share needs a human for the certificate anyway, and init-data.sh brings the
# stack up itself once it has seeded what the containers expect to find.
if [ ! -f "$SEEDED_SSL_CONF" ]; then
  echo
  echo "=== Stopping: $DATA_DIR has not been initialized ==="
  echo "The droplet is ready -- checkout, .env and .env.secrets are in place --"
  echo "but the share behind $DATA_DIR has nothing in it yet. That part needs a"
  echo "human, so it is not done at bootstrap. Run it from a terminal:"
  echo "  ~/init-data.sh"
  echo "It creates the data directories, seeds the TLS material, starts the"
  echo "stack and issues the certificate. This script takes over from the next"
  echo "boot on."
  exit 0
fi

echo "=== Starting the stack ==="
docker compose pull
docker compose up -d --remove-orphans

if ! sudo test -f "$RENEWAL_CONF"; then
  echo "=== No certificate for $DOMAIN yet ==="
  echo "webserver-secure will restart-loop until one is issued -- templates-secure/"
  echo "needs fullchain.pem and privkey.pem to load. :80 stays up to serve the ACME"
  echo "challenge, and the secure container comes up on its own once the"
  echo "certificate lands. To issue one:"
  echo "  ~/init-data.sh"
fi

echo "=== Setup complete ==="
